# Generated by Django 3.2.4 on 2022-12-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WritingGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_to_topic', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], verbose_name='Соответствие теме')),
                ('matching_args', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], verbose_name='Аргументация')),
                ('composition', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], verbose_name='Композиция')),
                ('speech_quality', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], verbose_name='Качество речи')),
                ('comment', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'оценка',
                'verbose_name_plural': 'оценки',
            },
        ),
    ]
