# Generated by Django 3.2.4 on 2022-12-13 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        ('writing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='writinggrade',
            name='essay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.essay', verbose_name='Сочинение'),
        ),
        migrations.AddField(
            model_name='writinggrade',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
