# Generated by Django 3.2.4 on 2022-12-13 13:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WritingGrade',
            new_name='Essay_Grade',
        ),
    ]
