# Generated by Django 3.2.4 on 2022-12-13 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writing', '0001_initial'),
        ('grades', '0003_rename_writinggrade_essay_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_grade',
            name='composition',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], verbose_name='композиция'),
        ),
        migrations.AlterField(
            model_name='essay_grade',
            name='essay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.essay', verbose_name='сочинение'),
        ),
        migrations.AlterField(
            model_name='essay_grade',
            name='matching_args',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], verbose_name='аргументация'),
        ),
        migrations.AlterField(
            model_name='essay_grade',
            name='relevance_to_topic',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], verbose_name='соответствие теме'),
        ),
        migrations.AlterField(
            model_name='essay_grade',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='оценено пользователем'),
        ),
        migrations.AlterField(
            model_name='essay_grade',
            name='speech_quality',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], verbose_name='качество речи'),
        ),
    ]
