# Generated by Django 3.2.4 on 2022-12-16 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_auto_20221213_1827'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0004_auto_20221213_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_grade',
            name='comment',
            field=models.TextField(verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='essay_grade',
            name='essay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='writing.essay', verbose_name='сочинение'),
        ),
        migrations.AlterField(
            model_name='essay_grade',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to=settings.AUTH_USER_MODEL, verbose_name='оценено пользователем'),
        ),
    ]
