# Generated by Django 3.2.4 on 2022-12-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_auto_20221216_1759'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='essay_grade',
            constraint=models.UniqueConstraint(fields=('reviewer', 'essay'), name='unique reviewer_essay pair'),
        ),
    ]
