# Generated by Django 3.2.4 on 2022-12-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_essay_grade_unique reviewer_essay pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_grade',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата публикации'),
        ),
    ]
