# Generated by Django 3.2.4 on 2022-12-22 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('essayfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay_report',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата жалобы'),
            preserve_default=False,
        ),
    ]
