# Generated by Django 3.2.4 on 2022-12-23 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0007_alter_essay_grade_pub_date'),
        ('essayfeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.IntegerField(choices=[(0, 'Оффтоп/Спам'), (1, 'Пропаганда/Реклама'), (2, 'Нецензурная лексика')], verbose_name='нарушение')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='дата жалобы')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.essay_grade', verbose_name='комментарий с нарушением')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор жалобы')),
            ],
        ),
    ]
