# Generated by Django 3.2.4 on 2022-12-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essayfeed', '0002_commentreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreport',
            options={'verbose_name': 'жалоба на комментарий', 'verbose_name_plural': 'жалобы на комментарии'},
        ),
    ]
