# Generated by Django 3.2.4 on 2022-12-22 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('essayfeed', '0002_essay_report_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay_report',
            name='intruder',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='users.profile', verbose_name='нарушитель'),
            preserve_default=False,
        ),
    ]
