# Generated by Django 3.2.4 on 2023-01-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essayfeed', '0003_alter_commentreport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_report',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Оффтоп/Спам'), (1, 'Пропаганда/Реклама'), (2, 'Нецензурная лексика'), (3, 'Плагиат')], verbose_name='нарушение'),
        ),
    ]
