# Generated by Django 3.2.4 on 2022-12-22 07:35

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('essayfeed', '0003_essay_report_intruder'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='essay_report',
            constraint=models.CheckConstraint(check=models.Q(('from_user', django.db.models.expressions.F('intruder')), _negated=True), name='intruder not equal sender'),
        ),
    ]
