# Generated by Django 3.2.4 on 2023-01-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essayfeed', '0004_alter_essay_report_reason'),
        ('essayfeed', '0004_auto_20230114_1251'),
    ]

    operations = [
    ]
