# Generated by Django 3.2.4 on 2022-12-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('D', 'danger'), ('S', 'success'), ('W', 'warning'), ('I', 'info')], help_text='на сочинение получена жалоба. статус сочинения', max_length=1, verbose_name='статус'),
        ),
    ]
