# Generated by Django 3.2.4 on 2022-12-13 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('section', models.ForeignKey(help_text='Раздел', on_delete=django.db.models.deletion.CASCADE, to='writing.section')),
            ],
            options={
                'verbose_name': 'тема',
                'verbose_name_plural': 'темы',
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(help_text='Вступление')),
                ('first_arg', models.TextField(help_text='1-ый аргумент')),
                ('second_arg', models.TextField(help_text='2-ой аргумент')),
                ('closing', models.TextField(help_text='Заключение')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default='автор неизвестен', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('grades', models.ManyToManyField(related_name='essaygrade', through='grades.WritingGrade', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.topic')),
            ],
            options={
                'verbose_name': 'сочинение',
                'verbose_name_plural': 'сочинения',
            },
        ),
    ]
