# Generated by Django 3.2.4 on 2022-12-13 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0004_auto_20221213_1827'),
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'раздел', 'verbose_name_plural': 'разделы'},
        ),
        migrations.AlterField(
            model_name='essay',
            name='author',
            field=models.ForeignKey(default='автор неизвестен', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='автор комментария'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='closing',
            field=models.TextField(help_text='Заключение', verbose_name='заключение'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='first_arg',
            field=models.TextField(help_text='1-ый аргумент', verbose_name='1-ый аргумент'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='grades',
            field=models.ManyToManyField(related_name='essaygrade', through='grades.Essay_Grade', to=settings.AUTH_USER_MODEL, verbose_name='оценки'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='intro',
            field=models.TextField(help_text='Вступление', verbose_name='вступление'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='second_arg',
            field=models.TextField(help_text='2-ой аргумент', verbose_name='2-ой аргумент'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.topic', verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=150, verbose_name='название раздела'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=150, verbose_name='название темы'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(help_text='раздел', on_delete=django.db.models.deletion.CASCADE, to='writing.section', verbose_name='раздел'),
        ),
    ]
