# Generated by Django 3.2.4 on 2022-12-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_auto_20221213_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='mentors_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта получателя'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата публикации'),
        ),
    ]
