# Generated by Django 3.2.4 on 2022-12-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_auto_20221220_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='mentors_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='почта получателя'),
        ),
    ]
