# Generated by Django 3.2.4 on 2023-02-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_alter_essay_mentors_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=250, verbose_name='название раздела'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=250, verbose_name='название темы'),
        ),
    ]
